liongram_/liongram_/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import mimetypes

mimetypes.add_type("application/javascript", ".js", True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),

    path("__debug__/", include("debug_toolbar.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

liongram_/myapp/urls.py
from django.urls import path
from myapp import views

urlpatterns = [
    path('',views.home, name='home'),
    path('new/', views.create, name='create'),
    path('list/',views.list, name='list'),
    path('<int:id>/',views.detail, name='detail'),
    path('<int:id>/edit/', views.update),
    path('<int:id>/delete/', views.delete),
]

liongram_/myapp/models.py
from django.db import models
from django.contrib.auth import get_user_model

User= get_user_model()

class Post(models.Model):
    img=models.ImageField(verbose_name='이미지', null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count= models.IntegerField(verbose_name='조회수', default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)
    
class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일')
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

liongram_/myapp/views.py
from django.shortcuts import render, redirect
from .models import Post

def home(request):

    post_list = Post.objects.all()
    context = {
        'post_list':post_list ,
    }

    return render(request, 'index.html', context)

def delete(request, id):
    return render(request, 'post/delete.html')

def update(request, id):
    return render(request,'post/form.html')

def create(request):
    if request.method =="GET":
        return render(request,'post/form.html')
    else:
        img = request.FILES.get('image')
        content = request.POST.get('content')

        Post.objects.create(
            img = img,
            content=content,
            writer = request.user
        )
        return redirect('home')
    

def list(request):
    post_list = Post.objects.all()
    context = {
        'post_list':post_list ,
    }
    return render(request,'post/list.html', context)

def detail(request, id):
    return render(request,'post/detail.html')

liongram_/myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %} | 라이언그램</title>
</head>
<body class="container">
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <div>
        <nav>
            <ul class="bottom-menu-group" >
                <li>
                    <img src="{% static 'icons/home_outlined_black_36dp.svg' %}" alt="홈">
                </li>
                <li>
                    <img src="{% static 'icons/search_outlined_black_36dp.svg' %}" alt="검색"/>
                </li>
                <li>
                    <a href="{% url 'create' %}"><img src="{% static 'icons/add_box_outlined_black_36dp.svg' %}" alt="글쓰기"/></a>
                </li>
                <li>
                    <img src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요"/>
                </li>
                <li>
                    <img src="{% static 'icons/account_circle_outlined_black_36dp.svg' %}" alt="프로필"/>
                </li>
            </ul>
        </nav>
    </div>
    <!-- {% if request.user.is_authenticated %}
        <div>
            {{ user.username }}님 환영합니다.
        </div>
    {% endif %} -->
</body>
</html>

liongram_/myapp/templates/index copy.html
{% extends 'base.html' %}
{% load static %}
{% block title %} home {% endblock %}

{% block content %}
<main>
    <div class="card-list">
        <div class="card">
            <div class="card__header">
                <img src="" alt="">
                <a href="#">
                    <span class="card__user-name">likelion</span>
                </a>
            </div>
            <div class="card__body">
                <div>
                    <img calss="card__image" src="http://via.placeholder.com/420x600" alt="">
                </div>
                <div class="card__btn-group">
                    <div>
                        <img src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="">
                        <img src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="">
                        <img src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="">
                    </div>
                    <div>
                        <img src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="">
                    </div>
                    <div class="card_content">
                        <span class="card__like-num">좋아요 00개</span>
                        <div class="card__main-text">
                            <p><span class="card__user-name">Likelion</span>{{"실무와 현업에서 필요로 하는 ...."}}</p>
                        </div>
                        <div>
                            <p>댓글 0개 모두 보기</p>
                            <ul class="card__comment-group">
                                <li>
                                    <p><span class="card__user-name">Likelion</span>댓글 내용...</p>
                                </li>
                            </ul>
                            <p>2023년 5월 14일</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>
{% endblock %}

liongram_/myapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} home {% endblock %}

{% block content %}
<main>
    <div class="card-list">
        {% for post in post_list %}
            {% include 'mixin/posts/post_card.html' %}
        {% endfor %}
    </div>
</main>
{% endblock %}

liongram_/myapp/templates/mixin/posts/post_card.html
{% load static %}
<div class="card">
    <div class="card__header">
        <img class="card__user-image" src="http://via.placeholder.com/32x32"/>
        <span class="card__user-name">{{post.writer}}</span>
    </div>
    <div class="card__body">
        <div>
            {% if post.img %}
            <img class="card__image" src="{{post.img.url}}">
            {% else %}
            <img class="card__image" src="http://via.placeholder.com/600x600">
            {% endif %}
        </div>
        <div class="card__btn-group">
            <div>
                <img class="card__btn" src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요"/>
                <img class="card__btn" src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="댓글"/>
                <img class="card__btn" src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="공유하기"/>
            </div>
            <div>
                <img class="card__btn" src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="북마크"/>
            </div>
        </div>
        <div class="card_content">
            <span class="card__like-num">좋아요 00개</span>
            <div class="card__main-text">
                <p><span class="card__user-name">Likelion</span>{{post.content}}</p>
            </div>
            <div>
                <p>댓글 {{ post.comment_set.all.count }}개 모두 보기</p>
                <ul class="card__comment-group" style="list-style: none;">
                    {% for comment in post.comment_set.all %}
                            <li><p><span class="card__user-name">{{post.writer}}</span>{{comment.content}}</p></li>
                    {% endfor %}
                        </ul>
            </div>
            <span class="card__created-at">{{ post.created_at|date:"Y년 m월 d일" }}</span>
        </div>
    </div>
</div>

liongram_/myapp/templates/post/delete.html
{% extends 'base.html' %}
{% block title %}글 목록{% endblock %}

{% block content %}




{% endblock %}

liongram_/myapp/templates/post/detail.html
{% extends 'base.html' %}
{% block title %}글 목록{% endblock %}

{% block content %}




{% endblock %}

liongram_/myapp/templates/post/form.html
{% extends 'base.html' %}
{% block title %}글 입력{% endblock %}

{% block content %}
<h1> Post 입력</h1>
<form action="{% url 'create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label for="id_image">이미지</label>
        <input type="file" name="image" accept="image/*" id="id_image">
    </div>
    <div>
        <label for="id_content">내용</label>
        <textarea name="content" id="id_content" cols="30" rows="10"></textarea>
    </div>
    <div>
        <input type="submit">
    </div>
</form>
{% endblock %}

liongram_/myapp/templates/post/list.html
{% extends 'base.html' %}
{% block title %}글 목록{% endblock %}

{% block content %}

{% for post in post_list %}
<div>{{post.content}}</div>
<div>{{post.created_at}}</div>
<div>{{post.writer}}</div>
<div>{{post.id}}</div>


{% endfor %}


{% endblock %}